### ISSUE TITLE
instant_ending/TH09: Unlock characters as expected

### ISSUE THREAD

**Issue by nmlgc** [thpatch/thcrap-tsa#14]
This game guards its character unlocks in some weird way, so that you don't actually unlock most of them by simply starting a new game from Stage 9 and viewing the ending. See ae8f89bfe39203365bf3bdc1d92a1d7d9bdd3609 for my previous failed attempts at fixing this.

Pretty much a very minor, needlessly perfectionist issue, since unlocking everything with Skipgame *does* work nicely, and translators will be using that patch anyway, or are already running on some fully unlocked score.dat.

**Comment by brliron** [comment]
Too minor to be fixed
