### ISSUE TITLE
TH18tr: Character portraits aren't properly aligned when replaced

### ISSUE THREAD

**Issue by coop152** [thpatch/thcrap-tsa#42]
(I dont know if this is a problem with the base patches or the patcher, or user error)
Replacing character portraits causes some inconsistent behaviour in the touhou 18 trial. 
Replacing reimu's base image causes this to happen:
![image](https://user-images.githubusercontent.com/40497580/113508922-9a133280-954a-11eb-9472-7612c7f73790.png)
Replacing reimu's face images doesn't seem to have any effect.
Replacing marisa's base image has a similar effect to reimu:
![image](https://user-images.githubusercontent.com/40497580/113509048-608ef700-954b-11eb-901c-b3b0d82ab686.png)
and face images don't seem to work either.
Sakuya's base image works fine:
![image](https://user-images.githubusercontent.com/40497580/113509116-b8c5f900-954b-11eb-9ca7-dd4de0f50dca.png)
and replacing her face images works, but they are offset to the left. (Didn't get a screenshot)
Sanae has a mixture:
![image](https://user-images.githubusercontent.com/40497580/113518044-b24f7580-957b-11eb-8f8d-57aa40bd0a71.png)
I've had no issues editing any other images.

**Comment by brliron** [comment]
I replaced every sprite with, well, themselves, and I didn't see any problem. I would bet on user error.
If you want, you can send your base and portrait images for Reimu and we can look at it

**Comment by coop152** [comment]
Here's the entire patch folder: [LOCAL.zip](https://github.com/thpatch/thcrap-tsa/files/6258108/LOCAL.zip)
I saved the images using GIMP's default png export settings, if that tells you anything.

**Comment by brliron** [comment]
When I extract the images with the last thtk/thanm, the face images have a huge empty space on the left, which yours don't have. I'm quite sure you need it.
For example, with reimu:
![image](https://user-images.githubusercontent.com/10382983/113639693-05a7ed80-967a-11eb-9439-5df206009434.png)

**Comment by coop152** [comment]
Ah, I see... touhouSE cropped the space out, so I assumed that was correct. Thank you for the help
