### ISSUE TITLE
TH175: Flandre's Scenario/355/en translation isn't showing up in-game

### ISSUE THREAD

**Issue by webbedspace** [thpatch/thcrap-tsa#49]
![2022-01-31 17_06_00-東方剛欲異聞　～ 水没した沈愁地獄](https://user-images.githubusercontent.com/83939/151782664-ea73b89d-8b72-4d76-81e3-a241e791f680.png)
This line (plus three subsequent lines) isn't being replaced by the en translation. All previous lines in this scenario are fine.

TH17.5 version: 1.04 Steam

**Comment by brliron** [comment]
This wasn't actually a duplicate of #167, it was an issue with the filename on the wiki. I fixed it just now.
