### ISSUE TITLE
prevent zun's mutex from resetting the config

### ISSUE THREAD

**Issue by DankRank** [thpatch/thcrap-tsa#52]
me when I accidentally start the game twice and then the next time it runs in full screen and resizes all my windows:
![crying-emoji-dies](https://user-images.githubusercontent.com/4050457/165106248-7a679d15-f86a-4adf-b924-f3e48a9433ef.gif)

**Comment by ManDude** [comment]
yes plz this happens all the time with pcb

**Comment by 32th-System** [comment]
Turns out the reason why this happens is because ZUN will do the mutex checking before loading the cfg, but always write a cfg on exit, even if no cfg is loaded
