### ISSUE TITLE
TH185/???: Game will create window outside the space available by monitors

### ISSUE THREAD

**Issue by 32th-System** [thpatch/thcrap-tsa#58]
The game will store the last position of it's window in it's .cfg file and pass it as the X and Y parameters for CreateWindowExA. The problem is that the game won't do things like check if that position is within any monitor plugged in.

I last opened th185 with the game window on my second monitor. I no longer have it but the game will still try to place it's window in the space that monitor used to occupy. Because of that, the game is outside the boundaries of the monitor I still have, and therefore invisible and impossible to select

**Comment by nmlgc** [comment]
[thcrap_tsa has had a workaround for this issue for a long time.](https://github.com/thpatch/thcrap/blob/2d8becee1e3e62857dd93ddf0349fb7b196abded/thcrap_tsa/src/win32_tsa.cpp#L24-L139) Did this game start using new Win32 functions?

**Comment by 32th-System** [comment]
I didn't know
